name: warborne-tools
services:
  - name: web
    image:
      buildpack: heroku/python
    run: python manage.py migrate && python manage.py create_bot_config && gunicorn warborne_tools.wsgi:application --bind 0.0.0.0:$PORT
    envs:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: NODE_VERSION
        value: "18"
    http_port: 8000
    envs:
      - key: SECRET_KEY
        value: $SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: $ALLOWED_HOSTS
      - key: DJANGO_SETTINGS_MODULE
        value: "warborne_tools.settings_production"
      - key: DB_NAME
        value: "neondb"
      - key: DB_USER
        value: "neondb_owner"
      - key: DB_PASSWORD
        value: "npg_UplStky0JD9E"
      - key: DB_HOST
        value: "ep-broad-salad-adbzgcjy-pooler.c-2.us-east-1.aws.neon.tech"
      - key: DB_PORT
        value: "5432"
    regions:
      - fra
    scaling:
      min_scale: 1
      max_scale: 1
    resources:
      cpu: 1
      memory: 1
    healthcheck:
      http:
        path: /admin/
        port: 8000
        interval: 30s
        timeout: 10s
        retries: 3
