# Generated by Django 4.2.7 on 2025-09-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gearitem',
            options={'ordering': ['gear_type__category', 'rarity', 'required_level', 'name'], 'verbose_name': 'Gear Item', 'verbose_name_plural': 'Gear Items'},
        ),
        migrations.AlterModelOptions(
            name='gearmod',
            options={'ordering': ['rarity', 'mod_type', 'name'], 'verbose_name': 'Gear Mod', 'verbose_name_plural': 'Gear Mods'},
        ),
        migrations.AlterModelOptions(
            name='geartype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Gear Type', 'verbose_name_plural': 'Gear Types'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['in_game_name'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='playergear',
            options={'ordering': ['-is_equipped', 'gear_item__name'], 'verbose_name': 'Player Gear', 'verbose_name_plural': 'Player Gear'},
        ),
        migrations.AlterField(
            model_name='gearitem',
            name='damage',
            field=models.IntegerField(default=0, help_text='Base damage of the item'),
        ),
        migrations.AlterField(
            model_name='gearitem',
            name='defense',
            field=models.IntegerField(default=0, help_text='Base defense of the item'),
        ),
        migrations.AlterField(
            model_name='gearitem',
            name='energy_bonus',
            field=models.IntegerField(default=0, help_text='Energy bonus'),
        ),
        migrations.AlterField(
            model_name='gearitem',
            name='health_bonus',
            field=models.IntegerField(default=0, help_text='Health bonus'),
        ),
        migrations.AlterField(
            model_name='gearitem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20),
        ),
        migrations.AlterField(
            model_name='gearmod',
            name='mod_type',
            field=models.CharField(choices=[('damage', 'Damage'), ('defense', 'Defense'), ('health', 'Health'), ('energy', 'Energy'), ('speed', 'Speed'), ('special', 'Special')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gearmod',
            name='rarity',
            field=models.CharField(choices=[('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='geartype',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory'), ('vehicle', 'Vehicle'), ('tactical', 'Tactical'), ('mod', 'Mod')], max_length=50),
        ),
        migrations.AlterField(
            model_name='guild',
            name='faction',
            field=models.CharField(choices=[('none', 'No Faction'), ('emberwild', 'Emberwild'), ('magnates', 'Magnates'), ('ashen', 'Ashen'), ('ironcreed', 'Ironcreed'), ('sirius', 'Sirius'), ('shroud', 'Shroud')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='guild',
            name='tag',
            field=models.CharField(help_text='Short guild tag (e.g., [WAR])', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.CharField(choices=[('none', 'No Faction'), ('emberwild', 'Emberwild'), ('magnates', 'Magnates'), ('ashen', 'Ashen'), ('ironcreed', 'Ironcreed'), ('sirius', 'Sirius'), ('shroud', 'Shroud')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the player', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_playstyle',
            field=models.CharField(blank=True, choices=[('pvp', 'PvP'), ('pve', 'PvE'), ('mixed', 'Mixed'), ('trading', 'Trading'), ('exploration', 'Exploration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('leader', 'Leader'), ('recruiter', 'Recruiter')], default='member', max_length=20),
        ),
    ]
