# Generated by Django 4.2.7 on 2025-09-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0006_remove_guild_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
