# Generated by Django 4.2.7 on 2025-09-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0007_remove_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_name',
            field=models.CharField(default='', help_text='Discord username (e.g., PlayerName#1234)', max_length=100),
        ),
    ]
