# Generated by Django 4.2.7 on 2025-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0012_gearitem_armor_gearitem_magic_resistance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_role',
            field=models.CharField(blank=True, choices=[('ranged_dps', 'Ranged DPS'), ('melee_dps', 'Melee DPS'), ('tank', 'Tank'), ('healer', 'Healer'), ('defensive_tank', 'Defensive Tank'), ('offensive_tank', 'Offensive Tank'), ('offensive_support', 'Offensive Support'), ('defensive_support', 'Defensive Support')], help_text='Primary role/playstyle in the game', max_length=20, null=True),
        ),
    ]
