# Generated by Django 4.2.7 on 2025-09-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0013_player_game_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Warborne Bot', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the bot is currently active')),
                ('bot_token', models.CharField(blank=True, help_text='Discord bot token (from environment)', max_length=200)),
                ('client_id', models.CharField(blank=True, help_text='Discord client ID (from environment)', max_length=100)),
                ('client_secret', models.CharField(blank=True, help_text='Discord client secret (from environment)', max_length=200)),
                ('command_prefix', models.CharField(default='/', help_text='Command prefix for the bot', max_length=10)),
                ('base_url', models.URLField(default='http://127.0.0.1:8000', help_text='Base URL for the application')),
                ('is_online', models.BooleanField(default=False, help_text='Whether the bot is currently online')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last heartbeat from the bot', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Last error message from the bot')),
                ('can_manage_messages', models.BooleanField(default=True)),
                ('can_embed_links', models.BooleanField(default=True)),
                ('can_attach_files', models.BooleanField(default=True)),
                ('can_read_message_history', models.BooleanField(default=True)),
                ('can_use_external_emojis', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discord Bot Configuration',
                'verbose_name_plural': 'Discord Bot Configurations',
            },
        ),
    ]
