# Generated by Django 4.2.7 on 2025-09-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0014_discordbotconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_user_id',
            field=models.BigIntegerField(blank=True, help_text='Discord User ID of the player owner', null=True),
        ),
    ]
