# Generated by Django 4.2.7 on 2025-09-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0015_add_discord_user_id_to_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('guild_war', 'Guild War'), ('pvp_fight', 'PvP Fight'), ('resource_farming', 'Resource Farming'), ('boss_raid', 'Boss Raid'), ('social_event', 'Social Event'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=50)),
                ('discord_message_id', models.BigIntegerField(blank=True, help_text='Discord message ID of the event post', null=True)),
                ('discord_channel_id', models.BigIntegerField(blank=True, help_text='Discord channel ID where event was posted', null=True)),
                ('created_by_discord_id', models.BigIntegerField(help_text='Discord User ID of event creator')),
                ('created_by_discord_name', models.CharField(help_text='Discord username of event creator', max_length=100)),
                ('event_datetime', models.DateTimeField(help_text='When the event will take place')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for the event', max_length=50)),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants (null = unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is still active')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Whether the event was cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.BigIntegerField(help_text='Discord User ID of participant')),
                ('discord_name', models.CharField(help_text='Discord username of participant', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the participant is still active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the participant', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='guilds.event')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='guilds.player')),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'ordering': ['joined_at'],
                'unique_together': {('event', 'discord_user_id')},
            },
        ),
    ]
