# Generated by Django 4.2.7 on 2025-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0016_add_event_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordbotconfig',
            name='event_announcements_channel_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the channel where event announcements are posted', null=True),
        ),
        migrations.AddField(
            model_name='discordbotconfig',
            name='general_channel_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the general channel for bot announcements', null=True),
        ),
        migrations.AddField(
            model_name='discordbotconfig',
            name='violence_bot_channel_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the violence-bot channel where events are created', null=True),
        ),
    ]
