# Generated by Django 4.2.7 on 2025-09-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0018_add_party_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Build title/name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Build description and strategy')),
                ('role', models.CharField(choices=[('ranged_dps', 'Ranged DPS'), ('melee_dps', 'Melee DPS'), ('tank', 'Tank'), ('healer', 'Healer'), ('defensive_tank', 'Defensive Tank'), ('offensive_tank', 'Offensive Tank'), ('offensive_support', 'Offensive Support'), ('defensive_support', 'Defensive Support')], help_text='Role this build is designed for', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this build is currently recommended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Admin', help_text='Who created this build recommendation', max_length=100)),
                ('template_player', models.ForeignKey(help_text='Player whose loadout serves as the template', on_delete=django.db.models.deletion.CASCADE, to='guilds.player')),
            ],
            options={
                'verbose_name': 'Recommended Build',
                'verbose_name_plural': 'Recommended Builds',
                'ordering': ['role', 'title'],
            },
        ),
    ]
