# Generated by Django 4.2.7 on 2025-09-20 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GearMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mod_type', models.CharField(choices=[('damage', 'Daño'), ('defense', 'Defensa'), ('health', 'Salud'), ('energy', 'Energía'), ('speed', 'Velocidad'), ('special', 'Especial')], max_length=20)),
                ('rarity', models.CharField(choices=[('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], max_length=20)),
                ('damage_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('health_bonus', models.IntegerField(default=0)),
                ('energy_bonus', models.IntegerField(default=0)),
                ('speed_bonus', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mod de Gear',
                'verbose_name_plural': 'Mods de Gear',
                'ordering': ['rarity', 'mod_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('weapon', 'Arma'), ('armor', 'Armadura'), ('accessory', 'Accesorio'), ('vehicle', 'Vehículo'), ('tactical', 'Táctico'), ('mod', 'Mod')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Gear',
                'verbose_name_plural': 'Tipos de Gear',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(help_text='Tag corto de la guild (ej: [WAR])', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('faction', models.CharField(choices=[('none', 'Sin Facción'), ('faction_1', 'Facción 1'), ('faction_2', 'Facción 2'), ('faction_3', 'Facción 3'), ('faction_4', 'Facción 4'), ('faction_5', 'Facción 5'), ('faction_6', 'Facción 6')], default='none', max_length=50)),
            ],
            options={
                'verbose_name': 'Guild',
                'verbose_name_plural': 'Guilds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_name', models.CharField(max_length=100, unique=True)),
                ('character_level', models.IntegerField(default=1)),
                ('faction', models.CharField(choices=[('none', 'Sin Facción'), ('faction_1', 'Facción 1'), ('faction_2', 'Facción 2'), ('faction_3', 'Facción 3'), ('faction_4', 'Facción 4'), ('faction_5', 'Facción 5'), ('faction_6', 'Facción 6')], default='none', max_length=50)),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('officer', 'Oficial'), ('leader', 'Líder'), ('recruiter', 'Reclutador')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_guild_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el jugador', null=True)),
                ('preferred_playstyle', models.CharField(blank=True, choices=[('pvp', 'PvP'), ('pve', 'PvE'), ('mixed', 'Mixto'), ('trading', 'Comercio'), ('exploration', 'Exploración')], max_length=50, null=True)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='guilds.guild')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['in_game_name'],
            },
        ),
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.CharField(choices=[('common', 'Común'), ('uncommon', 'Poco Común'), ('rare', 'Raro'), ('epic', 'Épico'), ('legendary', 'Legendario')], default='common', max_length=20)),
                ('required_level', models.IntegerField(default=1)),
                ('damage', models.IntegerField(default=0, help_text='Daño base del item')),
                ('defense', models.IntegerField(default=0, help_text='Defensa base del item')),
                ('health_bonus', models.IntegerField(default=0, help_text='Bonus de salud')),
                ('energy_bonus', models.IntegerField(default=0, help_text='Bonus de energía')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_craftable', models.BooleanField(default=False)),
                ('is_tradeable', models.BooleanField(default=True)),
                ('gear_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guilds.geartype')),
            ],
            options={
                'verbose_name': 'Item de Gear',
                'verbose_name_plural': 'Items de Gear',
                'ordering': ['gear_type__category', 'rarity', 'required_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('mod_slots_used', models.IntegerField(default=0)),
                ('mod_slots_max', models.IntegerField(default=0)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gear_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.gearitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to='guilds.player')),
            ],
            options={
                'verbose_name': 'Gear del Jugador',
                'verbose_name_plural': 'Gear de los Jugadores',
                'ordering': ['-is_equipped', 'gear_item__name'],
                'unique_together': {('player', 'gear_item')},
            },
        ),
    ]
