# Generated by Django 4.2.7 on 2025-09-20 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_alter_gearitem_options_alter_gearmod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_health', models.IntegerField(default=100)),
                ('base_energy', models.IntegerField(default=100)),
                ('base_damage', models.IntegerField(default=50)),
                ('base_defense', models.IntegerField(default=25)),
                ('base_speed', models.IntegerField(default=10)),
                ('special_abilities', models.TextField(blank=True, help_text='Special abilities or traits', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drifter',
                'verbose_name_plural': 'Drifters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gearitem',
            name='game_id',
            field=models.CharField(blank=True, help_text='Original game ID for reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to item icon', null=True),
        ),
        migrations.AddField(
            model_name='gearmod',
            name='game_id',
            field=models.CharField(blank=True, help_text='Original game ID for reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_drifter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_players', to='guilds.drifter'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_drifter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_players', to='guilds.drifter'),
        ),
    ]
