# Generated by Django 4.2.7 on 2025-09-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0003_drifter_gearitem_game_id_gearitem_icon_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='primary_drifter',
        ),
        migrations.RemoveField(
            model_name='player',
            name='secondary_drifter',
        ),
        migrations.AddField(
            model_name='player',
            name='drifter_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drifter_1_players', to='guilds.drifter', verbose_name='Drifter 1'),
        ),
        migrations.AddField(
            model_name='player',
            name='drifter_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drifter_2_players', to='guilds.drifter', verbose_name='Drifter 2'),
        ),
        migrations.AddField(
            model_name='player',
            name='drifter_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drifter_3_players', to='guilds.drifter', verbose_name='Drifter 3'),
        ),
        migrations.AddField(
            model_name='playergear',
            name='equipped_on_drifter',
            field=models.IntegerField(blank=True, choices=[(1, 'Drifter 1'), (2, 'Drifter 2'), (3, 'Drifter 3')], help_text='Which drifter is using this gear', null=True),
        ),
    ]
