# Generated by Django 4.2.7 on 2025-09-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_remove_player_primary_drifter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='casting_range',
            field=models.CharField(blank=True, help_text="Casting range (e.g., '12m', '7m')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='cooldown',
            field=models.CharField(blank=True, help_text="Cooldown time (e.g., '19s', '11s')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='detailed_stats',
            field=models.JSONField(blank=True, help_text='Detailed stats like attackPower, tenacity, etc.', null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='mana_cost',
            field=models.IntegerField(blank=True, help_text='Mana cost for skills', null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='skill_type',
            field=models.CharField(blank=True, help_text='Type of skill (basic, skill, ultimate, passive)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='tier_unlock',
            field=models.CharField(blank=True, help_text='Tier unlock requirement', max_length=10, null=True),
        ),
    ]
