# Generated by Django 4.2.7 on 2025-09-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0005_gearitem_casting_range_gearitem_cooldown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='tag',
        ),
    ]
