# Generated by Django 4.2.7 on 2025-09-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0008_player_discord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='preferred_playstyle',
        ),
    ]
