# Generated by Django 4.2.7 on 2025-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0009_remove_player_preferred_playstyle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gearitem',
            options={'ordering': ['gear_type__category', 'rarity', 'required_level', 'base_name'], 'verbose_name': 'Gear Item', 'verbose_name_plural': 'Gear Items'},
        ),
        migrations.AlterModelOptions(
            name='playergear',
            options={'ordering': ['-is_equipped', 'gear_item__base_name'], 'verbose_name': 'Player Gear', 'verbose_name_plural': 'Player Gear'},
        ),
        migrations.RemoveField(
            model_name='gearitem',
            name='name',
        ),
        migrations.AddField(
            model_name='gearitem',
            name='base_name',
            field=models.CharField(default='Unknown Item', help_text="Base item name (e.g., 'Energizer Boots')", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gearitem',
            name='skill_name',
            field=models.CharField(blank=True, help_text="Associated skill name (e.g., 'Vitality')", max_length=200),
        ),
    ]
