# Generated by Django 4.2.7 on 2025-09-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0010_alter_gearitem_options_alter_playergear_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearitem',
            name='damage',
            field=models.FloatField(default=0, help_text='Damage bonus percentage'),
        ),
    ]
