# Generated by Django 4.2.7 on 2025-09-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0011_alter_gearitem_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='armor',
            field=models.IntegerField(default=0, help_text='Armor value'),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='magic_resistance',
            field=models.IntegerField(default=0, help_text='Magic resistance value'),
        ),
        migrations.AddField(
            model_name='gearitem',
            name='mana_recovery',
            field=models.IntegerField(default=0, help_text='Mana recovery value'),
        ),
    ]
