# Generated by Django 4.2.7 on 2025-09-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0017_add_channel_config_to_discordbotconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_number', models.IntegerField(help_text='Party number within the event (1, 2, 3, etc.)')),
                ('max_members', models.IntegerField(default=15, help_text='Maximum members per party')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the party is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='guilds.event')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['party_number'],
                'unique_together': {('event', 'party_number')},
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(blank=True, choices=[('ranged_dps', 'Ranged DPS'), ('melee_dps', 'Melee DPS'), ('tank', 'Tank'), ('healer', 'Healer'), ('defensive_tank', 'Defensive Tank'), ('offensive_tank', 'Offensive Tank'), ('offensive_support', 'Offensive Support'), ('defensive_support', 'Defensive Support')], help_text="Role assigned in this party (may differ from player's default role)", max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the member is still active in the party')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_assignments', to='guilds.eventparticipant')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='guilds.party')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_assignments', to='guilds.player')),
            ],
            options={
                'verbose_name': 'Party Member',
                'verbose_name_plural': 'Party Members',
                'ordering': ['assigned_at'],
                'unique_together': {('party', 'event_participant')},
            },
        ),
    ]
