# Generated by Django 4.2.7 on 2025-09-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0019_recommendedbuild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedbuild',
            name='template_player',
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='boots',
            field=models.ForeignKey(blank=True, help_text='Boots for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_boots', to='guilds.gearitem'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='chest',
            field=models.ForeignKey(blank=True, help_text='Chest piece for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_chest', to='guilds.gearitem'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='consumable',
            field=models.ForeignKey(blank=True, help_text='Consumable for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_consumable', to='guilds.gearitem'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='drifter',
            field=models.ForeignKey(blank=True, help_text='Primary drifter for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guilds.drifter'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='helmet',
            field=models.ForeignKey(blank=True, help_text='Helmet for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_helmet', to='guilds.gearitem'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='mod1',
            field=models.ForeignKey(blank=True, help_text='Mod 1 for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_mod1', to='guilds.gearmod'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='mod2',
            field=models.ForeignKey(blank=True, help_text='Mod 2 for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_mod2', to='guilds.gearmod'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='mod3',
            field=models.ForeignKey(blank=True, help_text='Mod 3 for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_mod3', to='guilds.gearmod'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='mod4',
            field=models.ForeignKey(blank=True, help_text='Mod 4 for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_mod4', to='guilds.gearmod'),
        ),
        migrations.AddField(
            model_name='recommendedbuild',
            name='weapon',
            field=models.ForeignKey(blank=True, help_text='Weapon for this build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_builds_weapon', to='guilds.gearitem'),
        ),
    ]
