# Generated by Django 4.2.7 on 2025-09-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0020_remove_recommendedbuild_template_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(help_text='When the event will take place (UTC)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='UTC', help_text="IANA timezone name (e.g., 'America/New_York')", max_length=50),
        ),
    ]
