# Generated by Django 4.2.7 on 2025-09-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0021_alter_event_event_datetime_alter_event_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPartyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_count', models.IntegerField(default=0, help_text='Number of tanks per party (0 = filler)')),
                ('healer_count', models.IntegerField(default=2, help_text='Number of healers per party (0 = filler)')),
                ('ranged_dps_count', models.IntegerField(default=0, help_text='Number of ranged DPS per party (0 = filler)')),
                ('melee_dps_count', models.IntegerField(default=0, help_text='Number of melee DPS per party (0 = filler)')),
                ('defensive_tank_count', models.IntegerField(default=2, help_text='Number of defensive tanks per party (0 = filler)')),
                ('offensive_tank_count', models.IntegerField(default=2, help_text='Number of offensive tanks per party (0 = filler)')),
                ('offensive_support_count', models.IntegerField(default=0, help_text='Number of offensive support per party (0 = filler)')),
                ('defensive_support_count', models.IntegerField(default=0, help_text='Number of defensive support per party (0 = filler)')),
                ('guild_split', models.BooleanField(default=False, help_text='Whether to create separate parties for each guild')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_configuration', to='guilds.event')),
            ],
            options={
                'verbose_name': 'Event Party Configuration',
                'verbose_name_plural': 'Event Party Configurations',
            },
        ),
    ]
