# Generated by Django 4.2.7 on 2025-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0022_eventpartyconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpartyconfiguration',
            name='tank_count',
        ),
        migrations.AlterField(
            model_name='partymember',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('ranged_dps', 'Ranged DPS'), ('melee_dps', 'Melee DPS'), ('healer', 'Healer'), ('defensive_tank', 'Defensive Tank'), ('offensive_tank', 'Offensive Tank'), ('offensive_support', 'Offensive Support'), ('defensive_support', 'Defensive Support')], help_text="Role assigned in this party (may differ from player's default role)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_role',
            field=models.CharField(blank=True, choices=[('ranged_dps', 'Ranged DPS'), ('melee_dps', 'Melee DPS'), ('healer', 'Healer'), ('defensive_tank', 'Defensive Tank'), ('offensive_tank', 'Offensive Tank'), ('offensive_support', 'Offensive Support'), ('defensive_support', 'Defensive Support')], help_text='Primary role/playstyle in the game', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedbuild',
            name='role',
            field=models.CharField(choices=[('ranged_dps', 'Ranged DPS'), ('melee_dps', 'Melee DPS'), ('healer', 'Healer'), ('defensive_tank', 'Defensive Tank'), ('offensive_tank', 'Offensive Tank'), ('offensive_support', 'Offensive Support'), ('defensive_support', 'Defensive Support')], help_text='Role this build is designed for', max_length=20),
        ),
    ]
