# Generated by Django 4.2.7 on 2025-09-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0023_remove_eventpartyconfiguration_tank_count_and_more'),
    ]

    operations = [
    ]
