# Generated by Django 4.2.7 on 2025-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0024_auto_20250923_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_name',
            field=models.CharField(blank=True, help_text="Custom name for the party (e.g., Tommy's Party)", max_length=100, null=True),
        ),
    ]
