# Generated by Django 4.2.7 on 2025-09-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0025_party_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='is_active',
        ),
    ]
