# Generated by Django 4.2.7 on 2025-09-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0026_remove_eventparticipant_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'discord_name')},
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='discord_user_id',
            field=models.BigIntegerField(blank=True, help_text='Discord User ID of participant', null=True),
        ),
    ]
