# Generated by Django 4.2.7 on 2025-09-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0027_make_discord_user_id_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymember',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Whether this member is the party leader'),
        ),
    ]
