# Generated by Django 4.2.7 on 2025-09-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0028_partymember_is_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start Bot'), ('stop', 'Stop Bot'), ('restart', 'Restart Bot'), ('status_check', 'Check Bot Status'), ('command_processed', 'Command Processed'), ('error', 'Error'), ('info', 'Info'), ('warning', 'Warning')], max_length=20)),
                ('message', models.TextField(help_text='Log message or description')),
                ('details', models.JSONField(blank=True, help_text='Additional details as JSON', null=True)),
                ('user', models.CharField(blank=True, help_text='User who triggered the action', max_length=100)),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discord Bot Log',
                'verbose_name_plural': 'Discord Bot Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
