# Generated by Django 4.2.7 on 2025-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0029_discordbotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='tier',
            field=models.CharField(choices=[('II', 'Tier II'), ('III', 'Tier III'), ('IV', 'Tier IV'), ('V', 'Tier V'), ('VI', 'Tier VI'), ('VII', 'Tier VII'), ('VIII', 'Tier VIII')], default='II', help_text='Item tier for gear power calculation', max_length=5),
        ),
    ]
