# Generated by Django 4.2.7 on 2025-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0031_alter_gearitem_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='item_level',
            field=models.IntegerField(default=30, help_text='Item level (1-30) for gear power calculation'),
        ),
    ]
