# Generated by Django 4.2.7 on 2025-09-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0032_add_item_level_to_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_gear_power',
            field=models.IntegerField(default=0, help_text='Total power from all equipped gear'),
        ),
    ]
