# Generated by Django 4.2.7 on 2025-09-25 01:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0033_add_total_gear_power_to_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftedLegendaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('judicator', 'Judicator'), ('sovereigns_radiance', 'Sovereigns Radiance'), ('voideye', 'Voideye'), ('prismcloak', 'Prismcloak'), ('wreckingsaw', 'Wreckingsaw'), ('wingblade', 'Wingblade'), ('abyssal_conduit', 'Abyssal Conduit'), ('thunderlords_wrath', 'Thunderlords Wrath'), ('menders_ruin', 'Menders Ruin'), ('eclypse_bow', 'Eclypse Bow'), ('corrosive_piercer', 'Corrosive Piercer'), ('phantom_spear', 'Phantom Spear'), ('spirits_call', 'Spirits Call'), ('sanctuary_of_growth', 'Sanctuary of Growth'), ('bloodthirst', 'Bloodthirst'), ('scarlet_hunger', 'Scarlet Hunger'), ('solarflare', 'Solarflare'), ('molten_mortar', 'Molten Mortar'), ('glacier_spark', 'Glacier Spark'), ('frosts_caller', 'Frosts Caller'), ('necromist', 'Necromist'), ('withermaul', 'Withermaul'), ('celestial_redeemer', 'Celestial Redeemer'), ('sol_protector', 'Sol Protector'), ('stormveil_mask', 'Stormveil Mask'), ('wardens_gaze', 'Wardens Gaze'), ('ironwill_veil', 'Ironwill Veil'), ('folly_helm', 'Folly Helm'), ('sanctum_shroud', 'Sanctum Shroud'), ('twilight_mantle', 'Twilight Mantle'), ('wardens_shell', 'Wardens Shell'), ('magsurge_armor', 'Magsurge Armor'), ('rangers_hide', 'Rangers Hide'), ('heros_embrace', 'Heros Embrace'), ('warding_shroud', 'Warding Shroud'), ('dreadcloak', 'Dreadcloak'), ('impact_heavy_boots', 'Impact Heavy Boots'), ('avalanche_boots', 'Avalanche Boots'), ('evasion_striders', 'Evasion Striders'), ('exodrift_slippers', 'Exodrift Slippers'), ('phantomstep_boots', 'Phantomstep Boots'), ('savagefoot_boots', 'Savagefoot Boots')], max_length=50)),
                ('crafted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the crafting', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafted_items', to='guilds.player')),
            ],
            options={
                'verbose_name': 'Crafted Legendary Item',
                'verbose_name_plural': 'Crafted Legendary Items',
                'ordering': ['-crafted_date', 'player__discord_name', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='LegendaryBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('judicator', 'Judicator'), ('sovereigns_radiance', 'Sovereigns Radiance'), ('voideye', 'Voideye'), ('prismcloak', 'Prismcloak'), ('wreckingsaw', 'Wreckingsaw'), ('wingblade', 'Wingblade'), ('abyssal_conduit', 'Abyssal Conduit'), ('thunderlords_wrath', 'Thunderlords Wrath'), ('menders_ruin', 'Menders Ruin'), ('eclypse_bow', 'Eclypse Bow'), ('corrosive_piercer', 'Corrosive Piercer'), ('phantom_spear', 'Phantom Spear'), ('spirits_call', 'Spirits Call'), ('sanctuary_of_growth', 'Sanctuary of Growth'), ('bloodthirst', 'Bloodthirst'), ('scarlet_hunger', 'Scarlet Hunger'), ('solarflare', 'Solarflare'), ('molten_mortar', 'Molten Mortar'), ('glacier_spark', 'Glacier Spark'), ('frosts_caller', 'Frosts Caller'), ('necromist', 'Necromist'), ('withermaul', 'Withermaul'), ('celestial_redeemer', 'Celestial Redeemer'), ('sol_protector', 'Sol Protector'), ('stormveil_mask', 'Stormveil Mask'), ('wardens_gaze', 'Wardens Gaze'), ('ironwill_veil', 'Ironwill Veil'), ('folly_helm', 'Folly Helm'), ('sanctum_shroud', 'Sanctum Shroud'), ('twilight_mantle', 'Twilight Mantle'), ('wardens_shell', 'Wardens Shell'), ('magsurge_armor', 'Magsurge Armor'), ('rangers_hide', 'Rangers Hide'), ('heros_embrace', 'Heros Embrace'), ('warding_shroud', 'Warding Shroud'), ('dreadcloak', 'Dreadcloak'), ('impact_heavy_boots', 'Impact Heavy Boots'), ('avalanche_boots', 'Avalanche Boots'), ('evasion_striders', 'Evasion Striders'), ('exodrift_slippers', 'Exodrift Slippers'), ('phantomstep_boots', 'Phantomstep Boots'), ('savagefoot_boots', 'Savagefoot Boots')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of blueprints for this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='guilds.player')),
            ],
            options={
                'verbose_name': 'Legendary Blueprint',
                'verbose_name_plural': 'Legendary Blueprints',
                'ordering': ['player__discord_name', 'item_name'],
                'unique_together': {('player', 'item_name')},
            },
        ),
    ]
