# Generated by Django 4.2.7 on 2025-09-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0034_craftedlegendaryitem_legendaryblueprint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CraftedLegendaryItem',
        ),
    ]
