# Generated by Django 4.2.7 on 2025-09-25 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guilds', '0035_delete_craftedlegendaryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crafter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('judicator', 'Judicator'), ('sovereigns_radiance', 'Sovereigns Radiance'), ('voideye', 'Voideye'), ('prismcloak', 'Prismcloak'), ('wreckingsaw', 'Wreckingsaw'), ('wingblade', 'Wingblade'), ('abyssal_conduit', 'Abyssal Conduit'), ('thunderlords_wrath', 'Thunderlords Wrath'), ('menders_ruin', 'Menders Ruin'), ('eclypse_bow', 'Eclypse Bow'), ('corrosive_piercer', 'Corrosive Piercer'), ('phantom_spear', 'Phantom Spear'), ('spirits_call', 'Spirits Call'), ('sanctuary_of_growth', 'Sanctuary of Growth'), ('bloodthirst', 'Bloodthirst'), ('scarlet_hunger', 'Scarlet Hunger'), ('solarflare', 'Solarflare'), ('molten_mortar', 'Molten Mortar'), ('glacier_spark', 'Glacier Spark'), ('frosts_caller', 'Frosts Caller'), ('necromist', 'Necromist'), ('withermaul', 'Withermaul'), ('celestial_redeemer', 'Celestial Redeemer'), ('sol_protector', 'Sol Protector'), ('stormveil_mask', 'Stormveil Mask'), ('wardens_gaze', 'Wardens Gaze'), ('ironwill_veil', 'Ironwill Veil'), ('folly_helm', 'Folly Helm'), ('sanctum_shroud', 'Sanctum Shroud'), ('twilight_mantle', 'Twilight Mantle'), ('wardens_shell', 'Wardens Shell'), ('magsurge_armor', 'Magsurge Armor'), ('rangers_hide', 'Rangers Hide'), ('heros_embrace', 'Heros Embrace'), ('warding_shroud', 'Warding Shroud'), ('dreadcloak', 'Dreadcloak'), ('impact_heavy_boots', 'Impact Heavy Boots'), ('avalanche_boots', 'Avalanche Boots'), ('evasion_striders', 'Evasion Striders'), ('exodrift_slippers', 'Exodrift Slippers'), ('phantomstep_boots', 'Phantomstep Boots'), ('savagefoot_boots', 'Savagefoot Boots')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who added this crafter', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafters', to='guilds.player')),
            ],
            options={
                'verbose_name': 'Crafter',
                'verbose_name_plural': 'Crafters',
                'ordering': ['item_name', 'player__discord_name'],
                'unique_together': {('player', 'item_name')},
            },
        ),
    ]
