# Generated by Django 4.2.7 on 2025-09-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0036_crafter'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='crypto_tommys',
            field=models.PositiveIntegerField(default=0, help_text='CryptoTommys points earned by the player'),
        ),
    ]
