# Generated by Django 4.2.7 on 2025-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0037_add_crypto_tommys_to_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points_per_participant',
            field=models.PositiveIntegerField(default=0, help_text='CryptoTommys points awarded to each participant'),
        ),
    ]
