# Generated by Django 4.2.7 on 2025-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0038_add_points_per_participant_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banner_picture',
            field=models.URLField(blank=True, help_text="URL to player's banner picture", null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="URL to player's profile picture", null=True),
        ),
    ]
