# Generated by Django 4.2.7 on 2025-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0039_add_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Maximum party size for this event (null = default party size). This is NOT the event participant limit.', null=True),
        ),
    ]
