# Generated by Django 4.2.7 on 2025-10-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0040_update_event_max_participants_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the participant is currently active in the event'),
        ),
    ]
