# Generated by Django 4.2.7 on 2025-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0043_set_default_roles_and_make_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_role',
            field=models.CharField(choices=[('ranged_dps', 'Ranged DPS'), ('melee_dps', 'Melee DPS'), ('healer', 'Healer'), ('defensive_tank', 'Defensive Tank'), ('offensive_tank', 'Offensive Tank'), ('offensive_support', 'Offensive Support'), ('defensive_support', 'Defensive Support')], default='ranged_dps', help_text='Primary role/playstyle in the game', max_length=20),
        ),
    ]
