# Generated by Django 4.2.7 on 2025-10-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0044_alter_player_game_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Template description', null=True)),
                ('event_type', models.CharField(choices=[('guild_war', 'Guild War'), ('pvp_fight', 'PvP Fight'), ('resource_farming', 'Resource Farming'), ('boss_raid', 'Boss Raid'), ('social_event', 'Social Event'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=50)),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum party size for this template (null = default party size)', null=True)),
                ('points_per_participant', models.IntegerField(default=0, help_text='Points awarded per participant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_discord_id', models.BigIntegerField(default=0, help_text='Discord ID of template creator')),
                ('created_by_discord_name', models.CharField(default='Web User', help_text='Discord name of template creator', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is active')),
            ],
            options={
                'verbose_name': 'Event Template',
                'verbose_name_plural': 'Event Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
